// niri IPC wire types.
//
// Generated by hand from the `niri-ipc` crate at niri 26.4.0 (checked
// 2026-10-03 against niri-ipc/src/lib.rs). This header is the single place where
// the wire schema is transcribed; everything else in src/niri/ speaks these
// types. See docs/PROTOCOLS.md for the version-tolerance policy.
//
// Serde externally-tagged enums map onto QJsonObject as follows:
//
//   Rust                                    JSON                          Qt
//   ------------------------------------------------------------------------------------
//   Request::Version                         "Version"                    kind = Version
//   Request::Windows                        {"Windows": [...]}           kind = Windows
//   Request::Action(a)                      {"Action": { ... }}          kind = Action
//   Reply = Result<Response, String>        {"Ok": {...}} / {"Err": ".."}
//   Event::WorkspacesChanged{..}             {"WorkspacesChanged": {"workspaces":[..]}}
//
// The `kind` string is the *variant name*, so unknown variants are simply
// unrecognised kinds rather than parse errors. That is the whole
// version-tolerance strategy: a newer niri adds variants, we log them once and
// carry on (roadmap 4.4: "All parsers must tolerate unknown/missing fields").

#pragma once

#include <QJsonObject>
#include <QPair>
#include <QString>
#include <QStringList>
#include <QVector>

#include <cstdint>
#include <optional>

namespace kapah::niri {

// ---------------------------------------------------------------------------
// Requests
// ---------------------------------------------------------------------------

enum class RequestKind : quint8 {
    Unknown = 0,
    Version,
    Outputs,
    Workspaces,
    Windows,
    Layers,
    KeyboardLayouts,
    FocusedOutput,
    FocusedWindow,
    PickWindow,
    PickColor,
    Action,
    Output,
    EventStream,
    ReturnError,
    OverviewState,
    Casts,
};

QString requestKindToString(RequestKind kind);
// Encodes {"Kind": payload} for unit variants, {"Kind": obj} otherwise.
QByteArray encodeRequest(RequestKind kind, const QJsonObject &payload = {});

// ---------------------------------------------------------------------------
// Responses
// ---------------------------------------------------------------------------

enum class ResponseKind : quint8 {
    Error = 0,
    Handled,
    Version,
    Outputs,
    Workspaces,
    Windows,
    Layers,
    KeyboardLayouts,
    FocusedOutput,
    FocusedWindow,
    PickedWindow,
    PickedColor,
    OutputConfigChanged,
    OverviewState,
    Casts,
};

struct Reply {
    bool ok = false;
    ResponseKind kind = ResponseKind::Error;
    QString errorMessage;
    QJsonObject payload;

    static Reply fromJson(const QJsonObject &obj);
    QString describe() const;
};

// ---------------------------------------------------------------------------
// Models -- mirrors of the niri-ipc structs
// ---------------------------------------------------------------------------

struct Output {
    QString name;
    QString make;
    QString model;
    QString serial;
    int physicalWidthMm = 0;
    int physicalHeightMm = 0;
    bool hasPhysicalSize = false;
    QVector<QJsonObject> modes; // we never need more than the current one
    int currentModeIndex = -1;
    bool isCustomMode = false;
    bool vrrSupported = false;
    bool vrrEnabled = false;
    bool isDisabled = true; // logical == null
    // LogicalOutput
    int x = 0;
    int y = 0;
    int width = 0;
    int height = 0;
    double scale = 1.0;
    QString transform;

    int modeWidth() const;
    int modeHeight() const;
    double refreshHz() const;

    static std::optional<Output> fromJson(const QJsonObject &obj);
};

struct WindowLayout {
    bool hasPosInScrollingLayout = false;
    int column = 0;
    int tile = 0;
    double tileWidth = 0.0;
    double tileHeight = 0.0;
    int windowWidth = 0;
    int windowHeight = 0;
    bool hasTilePosInView = false;
    double viewX = 0.0;
    double viewY = 0.0;
    double offsetX = 0.0;
    double offsetY = 0.0;

    static WindowLayout fromJson(const QJsonObject &obj);
};

struct WindowInfo {
    quint64 id = 0;
    QString title;
    QString appId;
    bool hasPid = false;
    qint32 pid = 0;
    // Null when the window is on no workspace (e.g. a detached popup).
    bool hasWorkspace = false;
    quint64 workspaceId = 0;
    bool isFocused = false;
    bool isFloating = false;
    bool isUrgent = false;
    WindowLayout layout;
    bool hasFocusTimestamp = false;
    quint64 focusTimestampSecs = 0;
    quint32 focusTimestampNanos = 0;

    static WindowInfo fromJson(const QJsonObject &obj);
};

struct WorkspaceInfo {
    quint64 id = 0;
    int idx = 0;
    QString name;
    bool hasName = false;
    QString output;
    bool hasOutput = false;
    bool isUrgent = false;
    bool isActive = false;
    bool isFocused = false;
    bool hasActiveWindow = false;
    quint64 activeWindowId = 0;

    // Display name: explicit name if set, else the 1-based index.
    QString displayName() const;

    static WorkspaceInfo fromJson(const QJsonObject &obj);
};

struct KeyboardLayouts {
    QStringList names;
    int currentIndex = 0;

    // "English (US)" from "us" when available, else the raw XKB name.
    QString currentDisplayName() const;

    static KeyboardLayouts fromJson(const QJsonObject &obj);
};

struct LayerSurfaceInfo {
    QString nameSpace;
    QString output;
    QString layer;
    QString keyboardInteractivity;

    static LayerSurfaceInfo fromJson(const QJsonObject &obj);
};

struct CastInfo {
    quint64 streamId = 0;
    quint64 sessionId = 0;
    QString kind;
    QString targetDescription;
    bool isDynamicTarget = false;
    bool isActive = false;
    bool hasPid = false;
    qint32 pid = 0;
    bool hasPipeWireNode = false;
    quint32 pipeWireNodeId = 0;

    static CastInfo fromJson(const QJsonObject &obj);
};

struct OutputConfigChanged {
    QString result; // "Applied" | "OutputWasMissing"

    static OutputConfigChanged fromJson(const QJsonObject &obj);
};

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

enum class EventKind : quint8 {
    Unknown = 0,
    WorkspacesChanged,
    WorkspaceUrgencyChanged,
    WorkspaceActivated,
    WorkspaceActiveWindowChanged,
    WindowsChanged,
    WindowOpenedOrChanged,
    WindowClosed,
    WindowFocusChanged,
    WindowFocusTimestampChanged,
    WindowUrgencyChanged,
    WindowLayoutsChanged,
    KeyboardLayoutsChanged,
    KeyboardLayoutSwitched,
    OverviewOpenedOrClosed,
    ConfigLoaded,
    ScreenshotCaptured,
    CastsChanged,
    CastStartedOrChanged,
    CastStopped,
};

// Decoded union. Only the fields relevant to `kind` are populated.
//
// `unknownKind` holds the variant name when kind == Unknown, so the reducer can
// log it once and ignore it. This is the version-tolerance hook.
struct Event {
    EventKind kind = EventKind::Unknown;
    QString unknownKind;

    // WorkspacesChanged / WindowsChanged / CastsChanged
    QVector<WorkspaceInfo> workspaces;
    QVector<WindowInfo> windows;
    QVector<CastInfo> casts;

    // Scalar fields, reused across variants. Names mirror the Rust variants so
    // the mapping is checkable against niri-ipc/src/lib.rs.
    quint64 id = 0;
    bool hasId = false; // id: Option<u64>
    quint64 workspaceId = 0;
    bool urgent = false;
    bool focused = false;
    bool isOpen = false;
    int index = 0;
    QString path;
    bool hasPath = false;
    WindowInfo window;
    bool failed = false;
    KeyboardLayouts keyboardLayouts;
    // WindowFocusTimestampChanged
    bool hasTimestamp = false;
    quint64 timestampSecs = 0;
    quint32 timestampNanos = 0;
    // WindowLayoutsChanged
    QVector<QPair<quint64, WindowLayout>> layoutChanges;

    // Returns false and sets `ok` to false only when the JSON is not an object.
    // An unknown variant yields kind == Unknown with unknownKind set.
    static Event fromJson(const QJsonObject &obj, bool *ok = nullptr);

    QString kindToString() const;
};

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

// The subset of niri's 141 actions that this shell sends. The enum is
// deliberately not exhaustive: adding variants here is the only change needed
// when niri grows an action. `actionToJson` maps id -> the exact Rust variant
// spelling, which must match niri-ipc's serde rename.
enum class ActionId : quint16 {
    Unknown = 0,

    // Session
    Quit,
    PowerOffMonitors,
    PowerOnMonitors,

    // Windows
    CloseWindow,
    FullscreenWindow,
    ToggleWindowedFullscreen,
    FocusWindow,
    FocusWindowInColumn,
    FocusWindowPrevious,
    FocusColumnLeft,
    FocusColumnRight,
    FocusColumnFirst,
    FocusColumnLast,
    FocusColumnRightOrFirst,
    FocusColumnLeftOrLast,
    FocusColumn,
    FocusWindowOrMonitorUp,
    FocusWindowOrMonitorDown,
    FocusWindowDown,
    FocusWindowUp,
    FocusWindowDownOrColumnLeft,
    FocusWindowDownOrColumnRight,
    FocusWindowUpOrColumnLeft,
    FocusWindowUpOrColumnRight,
    FocusWindowOrWorkspaceDown,
    FocusWindowOrWorkspaceUp,
    FocusWindowTop,
    FocusWindowBottom,
    FocusWindowUpOrBottom,
    MoveWindowUp,
    MoveWindowDown,
    ConsumeOrExpelWindowLeft,
    ConsumeOrExpelWindowRight,
    ConsumeWindowIntoColumn,
    ExpelWindowFromColumn,
    SwapWindowRight,
    SwapWindowLeft,
    ToggleColumnTabbedDisplay,
    SetColumnDisplay,
    CenterColumn,
    CenterWindow,
    CenterVisibleColumns,
    MaximizeColumn,
    MaximizeWindowToEdges,
    SwitchPresetColumnWidth,
    SwitchPresetColumnWidthBack,
    SwitchPresetWindowWidth,
    SwitchPresetWindowWidthBack,
    SwitchPresetWindowHeight,
    SwitchPresetWindowHeightBack,
    ExpandColumnToAvailableWidth,
    ToggleWindowFloating,
    MoveWindowToFloating,
    MoveWindowToTiling,
    FocusFloating,
    FocusTiling,
    SwitchFocusBetweenFloatingAndTiling,
    ToggleWindowUrgent,
    SetWindowUrgent,
    UnsetWindowUrgent,

    // Workspaces
    FocusWorkspaceDown,
    FocusWorkspaceUp,
    FocusWorkspace,
    FocusWorkspacePrevious,
    MoveWindowToWorkspaceDown,
    MoveWindowToWorkspaceUp,
    MoveWindowToWorkspace,
    MoveColumnToWorkspaceDown,
    MoveColumnToWorkspaceUp,
    MoveColumnToWorkspace,
    MoveWorkspaceDown,
    MoveWorkspaceUp,
    MoveWorkspaceToIndex,
    SetWorkspaceName,
    UnsetWorkspaceName,

    // Monitors
    FocusMonitorLeft,
    FocusMonitorRight,
    FocusMonitorDown,
    FocusMonitorUp,
    FocusMonitorPrevious,
    FocusMonitorNext,
    FocusMonitor,
    MoveWindowToMonitorLeft,
    MoveWindowToMonitorRight,
    MoveWindowToMonitorDown,
    MoveWindowToMonitorUp,
    MoveWindowToMonitorPrevious,
    MoveWindowToMonitorNext,
    MoveWindowToMonitor,
    MoveColumnToMonitorLeft,
    MoveColumnToMonitorRight,
    MoveColumnToMonitorDown,
    MoveColumnToMonitorUp,
    MoveColumnToMonitorPrevious,
    MoveColumnToMonitorNext,
    MoveColumnToMonitor,
    MoveWorkspaceToMonitorLeft,
    MoveWorkspaceToMonitorRight,
    MoveWorkspaceToMonitorDown,
    MoveWorkspaceToMonitorUp,
    MoveWorkspaceToMonitorPrevious,
    MoveWorkspaceToMonitorNext,
    MoveWorkspaceToMonitor,
    MoveWorkspaceToMonitor,

    // Sizing
    SetWindowWidth,
    SetWindowHeight,
    ResetWindowHeight,
    SetColumnWidth,

    // Layout / keyboard
    SwitchLayout,
    ShowHotkeyOverlay,

    // Overview
    ToggleOverview,
    OpenOverview,
    CloseOverview,

    // Misc
    Spawn,
    SpawnSh,
    Screenshot,
    ScreenshotScreen,
    ScreenshotWindow,
    ToggleKeyboardShortcutsInhibit,
    LoadConfigFile,
    StopCast,
    SetDynamicCastWindow,
    SetDynamicCastMonitor,
    ClearDynamicCastTarget,
    ToggleDebugTint,
    DebugToggleOpaqueRegions,
    DebugToggleDamage,
    ToggleWindowRuleOpacity,
    DebugOverridePressureDynamics,
};

// The exact serde spelling of the variant. These strings are load-bearing:
// they are what niri deserializes.
const char *actionIdToString(ActionId id);

// Builds the action object. Variants that take an `id: Option<u64>` (most window
// and workspace actions) accept `targetId` and `hasTargetId`.
QJsonObject buildAction(ActionId id, bool hasTargetId = false, quint64 targetId = 0,
    const QJsonObject &extra = {});

// Convenience wrappers with the signatures the UI actually wants.
QJsonObject actionFocusWorkspace(quint64 workspaceId);
QJsonObject actionFocusWindow(quint64 windowId);
QJsonObject actionCloseWindow(quint64 windowId);
QJsonObject actionFocusWorkspaceIndex(int index, bool hasIndex = true);
QJsonObject actionFocusMonitor(const QString &outputName);
QJsonObject actionSwitchLayout(const QString &target);
QJsonObject actionQuit(bool skipConfirmation = true);

// ---------------------------------------------------------------------------
// Version tolerance
// ---------------------------------------------------------------------------

struct VersionSupport {
    QString raw;          // e.g. "26.4.0" or "25.11 (git sha deadbeef)"
    int major = 0;
    int minor = 0;
    int patch = 0;
    bool parsed = false;
    bool belowMinimum = false;
    bool aboveTested = false;
    QString note;

    static VersionSupport parse(const QString &raw);
};

} // namespace kapah::niri